name: credit_card_minimalist
description: Beautiful credit card, completely editable, with all widgets ready to use, simple and pretty.
version: 1.2.3
homepage: https://github.com/Djcharles26/
repository : https://github.com/Djcharles26/credit_card.git

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  
  flutter:
    sdk: flutter
  credit_card_number_validator: ^1.0.4
  flare_flutter : ^3.0.0
  provider: ^5.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
    
flutter:

  assets:
    - lib/cardIcons/
